package knowledge

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"testing"

	"github.com/wellxie/agentmate/internal/llm"
	"github.com/wellxie/agentmate/internal/ownership"
)

// scriptedClient drives compilation from a fixed reply, so the tests exercise the
// real orchestration — identity reuse, check gating, activation, diff, rollback —
// without depending on a model being reachable or on it saying the same thing
// twice.
type scriptedClient struct {
	replies []string
	calls   int
	err     error
	model   string
}

func (c *scriptedClient) Complete(_ context.Context, _ []llm.Message, _ ...llm.Option) (*llm.Completion, error) {
	if c.err != nil {
		return nil, c.err
	}
	index := c.calls
	if index >= len(c.replies) {
		index = len(c.replies) - 1
	}
	c.calls++
	return &llm.Completion{
		Content: c.replies[index],
		Model:   c.Model(),
		Usage:   llm.Usage{PromptTokens: 100, CompletionTokens: 50, TotalTokens: 150},
	}, nil
}

func (c *scriptedClient) Model() string {
	if c.model == "" {
		return "scripted-compiler"
	}
	return c.model
}

func (c *scriptedClient) Configured() bool { return true }

// wikiReply renders a compiler reply citing the given source paths.
func wikiReply(pages ...map[string]any) string {
	payload, err := json.Marshal(map[string]any{"pages": pages})
	if err != nil {
		panic(err)
	}
	return string(payload)
}

func wikiPage(path, kind, title, body string, citedPaths []string, links []map[string]any) map[string]any {
	citations := make([]map[string]any, 0, len(citedPaths))
	for _, cited := range citedPaths {
		citations = append(citations, map[string]any{
			"document_path": cited,
			"claim":         "claim from " + cited,
			"excerpt":       "excerpt from " + cited,
		})
	}
	page := map[string]any{
		"path": path, "kind": kind, "title": title, "content": body,
		"citations": citations,
	}
	if links != nil {
		page["links"] = links
	}
	return page
}

// wikiSnapshot has two documents so link and citation rules have something to
// resolve against.
func wikiSnapshot(body string) SubmitSnapshotRequest {
	return SubmitSnapshotRequest{Files: []SnapshotFile{
		{Path: "KNOWLEDGE.yaml", Content: "name: wiki-kb\nprofile: wiki-test\ninclude:\n  - \"raw/**\"\n"},
		{Path: "raw/overview.md", Content: "# Overview\n\n" + body},
		{Path: "raw/details.md", Content: "# Details\n\nThe retention window is 30 days.\n"},
	}}
}

func newWikiService(t *testing.T, ctx context.Context, client llm.Client) *Service {
	t.Helper()
	pool := integrationPool(t, ctx)
	service := NewService(NewRepo(pool))
	// Reviewer intentionally absent: review never gates activation, so the
	// compile path must be fully exercisable without one.
	service.WithLLM(client, nil, llm.IndependenceUnavailable)
	return service
}

func seedWikiSource(t *testing.T, ctx context.Context, service *Service, owner ownership.Owner, name, body string) *KnowledgeSource {
	t.Helper()
	source := createIntegrationSource(t, ctx, service, owner, name)
	if _, err := service.SubmitSnapshot(ctx, owner, source.ID, wikiSnapshot(body)); err != nil {
		t.Fatalf("submit snapshot: %v", err)
	}
	refreshed, err := service.GetSource(ctx, owner.Account(), source.ID)
	if err != nil {
		t.Fatalf("reload source: %v", err)
	}
	return refreshed
}

func goodReply() string {
	return wikiReply(
		wikiPage("wiki/overview.md", PageKindSummary, "Overview", "Summary of the overview.",
			[]string{"raw/overview.md"},
			[]map[string]any{{"target_path": "wiki/retention.md", "link_type": LinkElaborates}}),
		wikiPage("wiki/retention.md", PageKindConcept, "Retention", "Retention is 30 days.",
			[]string{"raw/details.md"}, nil),
	)
}

// TestCompileSucceedsAndActivates is the happy path: check passes, the wiki is
// committed whole, index and log are generated by the platform, and the active
// pointer moves without anyone approving anything.
func TestCompileSucceedsAndActivates(t *testing.T) {
	ctx := context.Background()
	client := &scriptedClient{replies: []string{goodReply()}}
	service := newWikiService(t, ctx, client)
	pool := integrationPool(t, ctx)
	owner, cleanup := createKnowledgeIntegrationOwner(t, ctx, pool, "wiki-happy")
	defer cleanup()

	source := seedWikiSource(t, ctx, service, owner, "wiki-happy-kb", "Overview body.\n")

	response, err := service.Compile(ctx, owner, CompileRequest{SourceID: source.ID})
	if err != nil {
		t.Fatalf("compile: %v", err)
	}
	if response.Build.Status != BuildStatusSucceeded {
		t.Fatalf("expected succeeded, got %s (error=%q, checks=%s)",
			response.Build.Status, response.Build.Error, response.Build.CheckFailures)
	}
	if response.Build.CheckStatus != CheckStatusPassed {
		t.Fatalf("expected check passed, got %s", response.Build.CheckStatus)
	}
	if !response.Activated {
		t.Fatal("a build passing check must be activated automatically")
	}
	// Two model pages plus the generated index and log.
	if response.Build.PagesWritten != 4 {
		t.Fatalf("expected 4 pages written, got %d", response.Build.PagesWritten)
	}
	// Provenance must be complete: a build is not reproducible, so anything not
	// recorded here is unrecoverable.
	if response.Build.Model != client.Model() || response.Build.CompilerVersion != CompilerVersion ||
		response.Build.PromptVersion != PromptVersion {
		t.Fatalf("incomplete provenance: %+v", response.Build)
	}
	if response.Build.SourceRevisionID != *source.ActiveRevisionID {
		t.Fatal("build must record the raw revision it compiled")
	}
	if response.Build.RawPackageHash == "" {
		t.Fatal("build must record the raw package hash")
	}

	pages, err := service.ListPages(ctx, owner.Account(), response.Build.ID)
	if err != nil {
		t.Fatalf("list pages: %v", err)
	}
	byPath := make(map[string]WikiPage, len(pages.Items))
	for _, page := range pages.Items {
		byPath[page.Path] = page
	}
	for _, required := range []string{"wiki/index.md", "wiki/log.md", "wiki/overview.md", "wiki/retention.md"} {
		if _, ok := byPath[required]; !ok {
			t.Fatalf("missing page %s; got %v", required, pages.Items)
		}
	}

	// The log must stay greppable with plain unix tools: that is how an operator
	// reads it when the API is not at hand.
	logPage, err := service.GetPage(ctx, owner.Account(), response.Build.ID, "wiki/log.md")
	if err != nil {
		t.Fatalf("get log page: %v", err)
	}
	headings := 0
	for _, line := range strings.Split(logPage.Content, "\n") {
		if strings.HasPrefix(line, "## [") {
			headings++
		}
	}
	if headings < 3 {
		t.Fatalf("expected a greppable event heading per event, got %d in:\n%s", headings, logPage.Content)
	}

	// Citations must resolve to real documents, otherwise a generated page is
	// unverifiable and the whole layer is untrustworthy.
	overview, err := service.GetPage(ctx, owner.Account(), response.Build.ID, "wiki/overview.md")
	if err != nil {
		t.Fatalf("get overview page: %v", err)
	}
	if len(overview.Citations) != 1 || overview.Citations[0].DocumentID == nil {
		t.Fatalf("expected one resolved citation, got %+v", overview.Citations)
	}
	// Both link directions are needed for navigation.
	retention, err := service.GetPage(ctx, owner.Account(), response.Build.ID, "wiki/retention.md")
	if err != nil {
		t.Fatalf("get retention page: %v", err)
	}
	inbound := 0
	for _, link := range retention.Links {
		if link.Direction == "in" {
			inbound++
		}
	}
	if inbound == 0 {
		t.Fatalf("expected an inbound link on wiki/retention.md, got %+v", retention.Links)
	}

	refreshed, err := service.GetSource(ctx, owner.Account(), source.ID)
	if err != nil {
		t.Fatalf("reload source: %v", err)
	}
	if refreshed.ActiveBuildID == nil || *refreshed.ActiveBuildID != response.Build.ID {
		t.Fatal("source active_build_id must point at the activated build")
	}
}

// TestCompileReusesIdenticalInputIdentity pins the idempotency key: same raw
// revision, profile version, compiler, model and prompt means no second call to
// the model. Content hashing could not do this — the same inputs produce
// different text every time.
func TestCompileReusesIdenticalInputIdentity(t *testing.T) {
	ctx := context.Background()
	client := &scriptedClient{replies: []string{goodReply()}}
	service := newWikiService(t, ctx, client)
	pool := integrationPool(t, ctx)
	owner, cleanup := createKnowledgeIntegrationOwner(t, ctx, pool, "wiki-identity")
	defer cleanup()

	source := seedWikiSource(t, ctx, service, owner, "wiki-identity-kb", "Overview body.\n")

	first, err := service.Compile(ctx, owner, CompileRequest{SourceID: source.ID})
	if err != nil {
		t.Fatalf("first compile: %v", err)
	}
	second, err := service.Compile(ctx, owner, CompileRequest{SourceID: source.ID})
	if err != nil {
		t.Fatalf("second compile: %v", err)
	}
	if !second.Reused || second.Build.ID != first.Build.ID {
		t.Fatalf("expected reuse of build %s, got %+v", first.Build.ID, second)
	}
	if client.calls != 1 {
		t.Fatalf("expected exactly one model call, got %d", client.calls)
	}

	// force must bypass reuse, since the reason to force is a suspicion about the
	// previous output rather than a change in inputs.
	forced, err := service.Compile(ctx, owner, CompileRequest{SourceID: source.ID, Force: true})
	if err != nil {
		t.Fatalf("forced compile: %v", err)
	}
	if forced.Reused || forced.Build.ID == first.Build.ID {
		t.Fatal("force must produce a new build")
	}
	if client.calls != 2 {
		t.Fatalf("expected a second model call after force, got %d", client.calls)
	}
}

// TestCompileFailsCheckAndWritesNothing is the reason automatic activation is
// safe. A fabricated citation must fail the build, leave no pages behind, and
// leave the active pointer where it was.
func TestCompileFailsCheckAndWritesNothing(t *testing.T) {
	ctx := context.Background()
	fabricated := wikiReply(
		wikiPage("wiki/ghost.md", PageKindSummary, "Ghost", "Cites a document that does not exist.",
			[]string{"raw/does-not-exist.md"}, nil),
	)
	client := &scriptedClient{replies: []string{fabricated}}
	service := newWikiService(t, ctx, client)
	pool := integrationPool(t, ctx)
	owner, cleanup := createKnowledgeIntegrationOwner(t, ctx, pool, "wiki-check")
	defer cleanup()

	source := seedWikiSource(t, ctx, service, owner, "wiki-check-kb", "Overview body.\n")

	response, err := service.Compile(ctx, owner, CompileRequest{SourceID: source.ID})
	if err != nil {
		t.Fatalf("compile: %v", err)
	}
	if response.Build.Status != BuildStatusFailed || response.Build.CheckStatus != CheckStatusFailed {
		t.Fatalf("expected failed/failed, got %s/%s", response.Build.Status, response.Build.CheckStatus)
	}
	if response.Activated {
		t.Fatal("a build failing check must never be activated")
	}
	var failures []CheckFailure
	if err := json.Unmarshal(response.Build.CheckFailures, &failures); err != nil {
		t.Fatalf("decode check failures: %v", err)
	}
	found := false
	for _, failure := range failures {
		if failure.Rule == ruleCitationResolvable {
			found = true
		}
	}
	if !found {
		t.Fatalf("expected a %s failure, got %+v", ruleCitationResolvable, failures)
	}

	// No half-written wiki: an agent cannot tell that pages are missing, so it
	// would answer from an incomplete graph as if it were complete.
	pages, err := service.ListPages(ctx, owner.Account(), response.Build.ID)
	if err != nil {
		t.Fatalf("list pages: %v", err)
	}
	if len(pages.Items) != 0 {
		t.Fatalf("a failed build must write no pages, got %d", len(pages.Items))
	}

	// The failure is still auditable.
	events, err := service.ListBuildEvents(ctx, owner.Account(), response.Build.ID)
	if err != nil {
		t.Fatalf("list events: %v", err)
	}
	if len(events) != 0 {
		t.Fatalf("events are committed with the wiki, so a failed build has none; got %d", len(events))
	}

	// Activating it explicitly must be refused too: check is the gate regardless
	// of who asks.
	if _, err := service.ActivateBuild(ctx, owner, response.Build.ID); !errors.Is(err, ErrBuildNotActivatable) {
		t.Fatalf("expected ErrBuildNotActivatable, got %v", err)
	}
}

// TestCompileDiffAndRollback covers the two operations that exist because builds
// are not reproducible: explaining a change without re-running it, and reverting
// by moving a pointer.
func TestCompileDiffAndRollback(t *testing.T) {
	ctx := context.Background()
	changed := wikiReply(
		wikiPage("wiki/overview.md", PageKindSummary, "Overview", "A rewritten overview.",
			[]string{"raw/overview.md"}, nil),
		wikiPage("wiki/glossary.md", PageKindEntity, "Glossary", "Retention window: 30 days.",
			[]string{"raw/details.md"}, nil),
	)
	client := &scriptedClient{replies: []string{goodReply(), changed}}
	service := newWikiService(t, ctx, client)
	pool := integrationPool(t, ctx)
	owner, cleanup := createKnowledgeIntegrationOwner(t, ctx, pool, "wiki-diff")
	defer cleanup()

	source := seedWikiSource(t, ctx, service, owner, "wiki-diff-kb", "Overview body.\n")

	first, err := service.Compile(ctx, owner, CompileRequest{SourceID: source.ID})
	if err != nil {
		t.Fatalf("first compile: %v", err)
	}
	second, err := service.Compile(ctx, owner, CompileRequest{SourceID: source.ID, Force: true})
	if err != nil {
		t.Fatalf("second compile: %v", err)
	}
	if second.Build.Status != BuildStatusSucceeded {
		t.Fatalf("second build failed: %s / %s", second.Build.Error, second.Build.CheckFailures)
	}

	diff, err := service.DiffBuilds(ctx, owner.Account(), first.Build.ID, second.Build.ID)
	if err != nil {
		t.Fatalf("diff: %v", err)
	}
	if !containsString(diff.Added, "wiki/glossary.md") {
		t.Fatalf("expected wiki/glossary.md added, got %+v", diff)
	}
	if !containsString(diff.Removed, "wiki/retention.md") {
		t.Fatalf("expected wiki/retention.md removed, got %+v", diff)
	}
	if !containsString(diff.Changed, "wiki/overview.md") {
		t.Fatalf("expected wiki/overview.md changed, got %+v", diff)
	}

	// Omitting the baseline compares against the previous succeeded build, which
	// is the question an operator actually asks.
	defaulted, err := service.DiffBuilds(ctx, owner.Account(), "", second.Build.ID)
	if err != nil {
		t.Fatalf("default diff: %v", err)
	}
	if defaulted.FromBuildID != first.Build.ID {
		t.Fatalf("expected default baseline %s, got %s", first.Build.ID, defaulted.FromBuildID)
	}

	// Rollback is activation of an older build; the response reports the outgoing
	// pointer so the rollback itself can be undone.
	rolled, err := service.ActivateBuild(ctx, owner, first.Build.ID)
	if err != nil {
		t.Fatalf("rollback: %v", err)
	}
	if rolled.PreviousBuildID == nil || *rolled.PreviousBuildID != second.Build.ID {
		t.Fatalf("expected previous build %s, got %+v", second.Build.ID, rolled.PreviousBuildID)
	}
	refreshed, err := service.GetSource(ctx, owner.Account(), source.ID)
	if err != nil {
		t.Fatalf("reload source: %v", err)
	}
	if refreshed.ActiveBuildID == nil || *refreshed.ActiveBuildID != first.Build.ID {
		t.Fatal("rollback must move the active pointer back")
	}
}

// TestCompileModelFailureRecordsFailedBuild keeps the cost and the error of a
// failed attempt in the audit trail instead of discarding it.
func TestCompileModelFailureRecordsFailedBuild(t *testing.T) {
	ctx := context.Background()
	client := &scriptedClient{err: fmt.Errorf("provider timeout")}
	service := newWikiService(t, ctx, client)
	pool := integrationPool(t, ctx)
	owner, cleanup := createKnowledgeIntegrationOwner(t, ctx, pool, "wiki-modelfail")
	defer cleanup()

	source := seedWikiSource(t, ctx, service, owner, "wiki-modelfail-kb", "Overview body.\n")

	response, err := service.Compile(ctx, owner, CompileRequest{SourceID: source.ID})
	if err != nil {
		t.Fatalf("compile: %v", err)
	}
	if response.Build.Status != BuildStatusFailed {
		t.Fatalf("expected failed, got %s", response.Build.Status)
	}
	// check never ran, so its verdict stays pending rather than claiming a pass.
	if response.Build.CheckStatus != CheckStatusPending {
		t.Fatalf("expected pending check, got %s", response.Build.CheckStatus)
	}
	if !strings.Contains(response.Build.Error, "provider timeout") {
		t.Fatalf("expected the provider error to be recorded, got %q", response.Build.Error)
	}
}

// TestCompileWithoutCompilerIsUnavailable separates an operator configuration gap
// from a defect in the sources: no failed build is recorded, because nothing
// about the sources was wrong.
func TestCompileWithoutCompilerIsUnavailable(t *testing.T) {
	ctx := context.Background()
	pool := integrationPool(t, ctx)
	service := NewService(NewRepo(pool))
	owner, cleanup := createKnowledgeIntegrationOwner(t, ctx, pool, "wiki-nollm")
	defer cleanup()

	source := seedWikiSource(t, ctx, service, owner, "wiki-nollm-kb", "Overview body.\n")

	if _, err := service.Compile(ctx, owner, CompileRequest{SourceID: source.ID}); !errors.Is(err, ErrCompilerUnavailable) {
		t.Fatalf("expected ErrCompilerUnavailable, got %v", err)
	}
	builds, err := service.ListBuilds(ctx, owner.Account(), source.ID, 20, 0)
	if err != nil {
		t.Fatalf("list builds: %v", err)
	}
	if builds.Total != 0 {
		t.Fatalf("an unconfigured compiler must not record a build, got %d", builds.Total)
	}
}

// TestCompileRejectsIncrementalMode pins the refusal to silently downgrade: a
// caller that asked for incremental would otherwise believe it saved cost.
func TestCompileRejectsIncrementalMode(t *testing.T) {
	ctx := context.Background()
	client := &scriptedClient{replies: []string{goodReply()}}
	service := newWikiService(t, ctx, client)
	pool := integrationPool(t, ctx)
	owner, cleanup := createKnowledgeIntegrationOwner(t, ctx, pool, "wiki-incremental")
	defer cleanup()

	source := seedWikiSource(t, ctx, service, owner, "wiki-incremental-kb", "Overview body.\n")

	_, err := service.Compile(ctx, owner, CompileRequest{SourceID: source.ID, Mode: BuildModeIncremental})
	if err == nil || !strings.Contains(err.Error(), "not implemented") {
		t.Fatalf("expected an explicit refusal, got %v", err)
	}
	if client.calls != 0 {
		t.Fatalf("expected no model call, got %d", client.calls)
	}
}

func containsString(values []string, target string) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}

// TestCompileRejectsReservedPagePaths pins the ownership boundary between model
// and platform. A real qwen3.7-plus build wrote its own wiki/index.md, which
// collided with the generated one and failed the whole build on path_unique — a
// foreseeable model behaviour that must not make the system unusable. The page is
// dropped instead, and the drop is recorded rather than hidden.
func TestCompileRejectsReservedPagePaths(t *testing.T) {
	ctx := context.Background()
	reply := wikiReply(
		wikiPage("wiki/index.md", PageKindIndex, "My own index", "- everything", nil, nil),
		wikiPage("wiki/log.md", PageKindLog, "My own log", "stuff happened", nil, nil),
		wikiPage("wiki/overview.md", PageKindSummary, "Overview", "Summary of the overview.",
			[]string{"raw/overview.md"}, nil),
	)
	client := &scriptedClient{replies: []string{reply}}
	service := newWikiService(t, ctx, client)
	pool := integrationPool(t, ctx)
	owner, cleanup := createKnowledgeIntegrationOwner(t, ctx, pool, "wiki-reserved")
	defer cleanup()

	source := seedWikiSource(t, ctx, service, owner, "wiki-reserved-kb", "Overview body.\n")

	response, err := service.Compile(ctx, owner, CompileRequest{SourceID: source.ID})
	if err != nil {
		t.Fatalf("compile: %v", err)
	}
	if response.Build.Status != BuildStatusSucceeded {
		t.Fatalf("expected succeeded, got %s (%s / %s)",
			response.Build.Status, response.Build.Error, response.Build.CheckFailures)
	}
	// One model page survived, plus the platform's index and log.
	if response.Build.PagesWritten != 3 {
		t.Fatalf("expected 3 pages, got %d (%v)", response.Build.PagesWritten, response.Pages)
	}

	// The generated index must be the platform's, not the model's.
	index, err := service.GetPage(ctx, owner.Account(), response.Build.ID, "wiki/index.md")
	if err != nil {
		t.Fatalf("get index: %v", err)
	}
	if strings.Contains(index.Content, "everything") {
		t.Fatalf("the model's index survived: %s", index.Content)
	}
	if !strings.Contains(index.Content, "wiki/overview.md") {
		t.Fatalf("generated index must link every content page, got:\n%s", index.Content)
	}

	events, err := service.ListBuildEvents(ctx, owner.Account(), response.Build.ID)
	if err != nil {
		t.Fatalf("list events: %v", err)
	}
	rejected := make([]string, 0)
	for _, event := range events {
		if event.EventType == BuildEventPageRejected {
			rejected = append(rejected, event.PagePath)
		}
	}
	if len(rejected) != 2 {
		t.Fatalf("expected both reserved paths recorded as rejected, got %v", rejected)
	}
}

// TestCompileFailsWhenEveryPageIsRejected keeps the rejection from turning into a
// silently empty wiki: if nothing usable survives, that is a failed build.
func TestCompileFailsWhenEveryPageIsRejected(t *testing.T) {
	ctx := context.Background()
	reply := wikiReply(
		wikiPage("wiki/index.md", PageKindIndex, "Only an index", "- nothing", nil, nil),
	)
	client := &scriptedClient{replies: []string{reply}}
	service := newWikiService(t, ctx, client)
	pool := integrationPool(t, ctx)
	owner, cleanup := createKnowledgeIntegrationOwner(t, ctx, pool, "wiki-allrejected")
	defer cleanup()

	source := seedWikiSource(t, ctx, service, owner, "wiki-allrejected-kb", "Overview body.\n")

	response, err := service.Compile(ctx, owner, CompileRequest{SourceID: source.ID})
	if err != nil {
		t.Fatalf("compile: %v", err)
	}
	if response.Build.Status != BuildStatusFailed {
		t.Fatalf("expected failed, got %s", response.Build.Status)
	}
	if !strings.Contains(response.Build.Error, "no usable pages") {
		t.Fatalf("expected an explicit reason, got %q", response.Build.Error)
	}
}
