package knowledge

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/wellxie/agentmate/internal/llm"
)

// The compiler turns raw sources into a persistent wiki.
//
// The model is asked for one JSON document describing every page, its citations
// and its typed links. A single call keeps cross-page consistency achievable:
// asking page by page would mean the model cannot see what it already wrote, so
// links and contradiction notes would be guesses. The cost is a ceiling on
// corpus size per build, which is why incremental compilation (K3.4) matters.
//
// index and log are generated by us, not by the model. The index must cover every
// page, and the log must reflect what actually happened — neither is a judgement
// call, and letting the model produce them would make check's coverage rule test
// the model's diligence instead of the build's completeness.

const compileSystemPrompt = `You are a disciplined wiki maintainer for a knowledge base.

You are given the full text of a knowledge package's raw source documents. Build a
persistent, interlinked wiki from them.

Rules you must follow:
1. Every factual claim must be supported by a citation naming the source document
   path it came from. Never cite a path you were not given.
2. Do not invent facts. If the sources do not say something, leave it out.
3. When two sources disagree, create the pages for both positions and record a
   "contradicts" link between them with a note stating the specific disagreement.
4. Extract a separate "entity" page for a term that the sources treat as a known
   concept in two or more documents but never define in one place.
5. Write in the language of the source documents.
6. Page paths must start with "wiki/" and end with ".md".

Reply with a single JSON object and nothing else:
{
  "pages": [
    {
      "path": "wiki/<name>.md",
      "kind": "summary" | "entity" | "concept" | "overview" | "synthesis",
      "title": "<short title>",
      "content": "<markdown body>",
      "citations": [
        {"document_path": "<exact source path>", "heading_path": "<optional section>",
         "claim": "<the claim this supports>", "excerpt": "<short quote from the source>"}
      ],
      "links": [
        {"target_path": "wiki/<other>.md",
         "link_type": "references" | "contradicts" | "supersedes" | "elaborates" | "mentions_entity",
         "note": "<why, required for contradicts and supersedes>"}
      ]
    }
  ]
}`

// compilerOutput mirrors the JSON contract above. Parsing is deliberately
// tolerant of extra fields and strict about the ones that matter.
type compilerOutput struct {
	Pages []struct {
		Path      string `json:"path"`
		Kind      string `json:"kind"`
		Title     string `json:"title"`
		Content   string `json:"content"`
		Citations []struct {
			DocumentPath string `json:"document_path"`
			HeadingPath  string `json:"heading_path"`
			Claim        string `json:"claim"`
			Excerpt      string `json:"excerpt"`
		} `json:"citations"`
		Links []struct {
			TargetPath string `json:"target_path"`
			LinkType   string `json:"link_type"`
			Note       string `json:"note"`
		} `json:"links"`
	} `json:"pages"`
}

// buildCompilePrompt renders the raw documents for the model.
//
// Documents are truncated per document rather than globally so one long file
// cannot crowd the others out of the prompt entirely: a wiki built from a
// truncated view of half the corpus would look complete while being wrong.
func buildCompilePrompt(profile ProfileVersion, manifest Manifest, documents []KnowledgeDocument, perDocumentChars int) string {
	var builder strings.Builder
	fmt.Fprintf(&builder, "Knowledge base: %s\n", manifest.Name)
	if manifest.Description != "" {
		fmt.Fprintf(&builder, "Description: %s\n", manifest.Description)
	}
	if manifest.Language != "" {
		fmt.Fprintf(&builder, "Language: %s\n", manifest.Language)
	}
	fmt.Fprintf(&builder, "Citation policy: %s\n", profile.CitationPolicy)
	fmt.Fprintf(&builder, "Allowed page kinds: %s\n", strings.Join(profile.AllowedPageKinds, ", "))
	fmt.Fprintf(&builder, "Allowed link types: %s\n", strings.Join(profile.AllowedLinkTypes, ", "))
	fmt.Fprintf(&builder, "Maximum pages: %d\n", profile.MaxPages)
	if profile.Instructions != "" {
		fmt.Fprintf(&builder, "\nProfile instructions:\n%s\n", profile.Instructions)
	}

	builder.WriteString("\nSource documents:\n")
	for _, document := range documents {
		content := document.ContentSnapshot
		truncated := false
		if perDocumentChars > 0 && utf8.RuneCountInString(content) > perDocumentChars {
			content = string([]rune(content)[:perDocumentChars])
			truncated = true
		}
		fmt.Fprintf(&builder, "\n--- path: %s ---\n%s\n", document.Path, content)
		if truncated {
			// Say so explicitly: a model that believes it saw a whole document
			// will summarise the missing part with confidence.
			fmt.Fprintf(&builder, "[document truncated at %d characters]\n", perDocumentChars)
		}
	}
	return builder.String()
}

// compileWithModel runs one compilation call and normalises the result.
func (s *Service) compileWithModel(
	ctx context.Context, profile ProfileVersion, manifest Manifest, documents []KnowledgeDocument,
) ([]WikiPage, llm.Usage, error) {
	prompt := buildCompilePrompt(profile, manifest, documents, s.compilePerDocumentChars())

	completion, err := s.compiler.Complete(ctx, []llm.Message{
		{Role: "system", Content: compileSystemPrompt},
		{Role: "user", Content: prompt},
	}, llm.WithJSONObject())
	if err != nil {
		return nil, llm.Usage{}, err
	}

	output, err := parseCompilerOutput(completion.Content)
	if err != nil {
		return nil, completion.Usage, err
	}

	knownPaths := make(map[string]string, len(documents))
	for _, document := range documents {
		knownPaths[document.Path] = document.ID
	}

	pages := make([]WikiPage, 0, len(output.Pages))
	for _, raw := range output.Pages {
		path := strings.TrimSpace(raw.Path)
		if path == "" {
			continue
		}
		page := WikiPage{
			Path:    path,
			Kind:    strings.TrimSpace(strings.ToLower(raw.Kind)),
			Title:   strings.TrimSpace(raw.Title),
			Content: strings.TrimSpace(raw.Content),
		}
		for _, citation := range raw.Citations {
			documentPath := strings.TrimSpace(citation.DocumentPath)
			if documentPath == "" {
				continue
			}
			item := PageCitation{
				DocumentPath: documentPath,
				HeadingPath:  strings.TrimSpace(citation.HeadingPath),
				Claim:        strings.TrimSpace(citation.Claim),
				Excerpt:      strings.TrimSpace(citation.Excerpt),
			}
			// Resolve to a document ID where possible. An unresolved path is kept
			// rather than dropped so check can report exactly which citation was
			// fabricated instead of only that some page lacked citations.
			if id, ok := knownPaths[documentPath]; ok {
				item.DocumentID = &id
			}
			page.Citations = append(page.Citations, item)
		}
		for _, link := range raw.Links {
			target := strings.TrimSpace(link.TargetPath)
			if target == "" {
				continue
			}
			page.Links = append(page.Links, PageLink{
				TargetPath: target,
				LinkType:   strings.TrimSpace(strings.ToLower(link.LinkType)),
				Note:       strings.TrimSpace(link.Note),
			})
		}
		page.ContentHash = hashContent(page.Content)
		pages = append(pages, page)
	}

	sort.Slice(pages, func(i, j int) bool { return pages[i].Path < pages[j].Path })
	return pages, completion.Usage, nil
}

// parseCompilerOutput decodes the model's reply.
//
// Providers sometimes wrap JSON in a fenced code block despite being asked not
// to, so the fence is stripped before decoding. Anything else is a hard error:
// silently accepting a partial parse would produce a wiki missing pages that
// nobody notices.
func parseCompilerOutput(content string) (*compilerOutput, error) {
	trimmed := strings.TrimSpace(content)
	if strings.HasPrefix(trimmed, "```") {
		trimmed = strings.TrimPrefix(trimmed, "```json")
		trimmed = strings.TrimPrefix(trimmed, "```")
		if index := strings.LastIndex(trimmed, "```"); index >= 0 {
			trimmed = trimmed[:index]
		}
		trimmed = strings.TrimSpace(trimmed)
	}
	var output compilerOutput
	if err := json.Unmarshal([]byte(trimmed), &output); err != nil {
		return nil, fmt.Errorf("compiler output is not valid JSON: %w", err)
	}
	if len(output.Pages) == 0 {
		return nil, fmt.Errorf("compiler returned no pages")
	}
	return &output, nil
}

// buildIndexPage renders the content-oriented catalogue.
//
// We generate it rather than asking the model to, because check requires the
// index to cover every page: if the model wrote it, that rule would be testing
// the model's diligence rather than the build's completeness.
func buildIndexPage(manifest Manifest, pages []WikiPage) WikiPage {
	byKind := make(map[string][]WikiPage)
	for _, page := range pages {
		byKind[page.Kind] = append(byKind[page.Kind], page)
	}
	kinds := make([]string, 0, len(byKind))
	for kind := range byKind {
		kinds = append(kinds, kind)
	}
	sort.Strings(kinds)

	var builder strings.Builder
	name := manifest.Name
	if name == "" {
		name = "Knowledge base"
	}
	fmt.Fprintf(&builder, "# %s index\n", name)
	if manifest.Description != "" {
		fmt.Fprintf(&builder, "\n%s\n", manifest.Description)
	}

	index := WikiPage{Path: "wiki/index.md", Kind: PageKindIndex, Title: name + " index"}
	for _, kind := range kinds {
		group := byKind[kind]
		sort.Slice(group, func(i, j int) bool { return group[i].Path < group[j].Path })
		fmt.Fprintf(&builder, "\n## %s\n\n", kind)
		for _, page := range group {
			title := page.Title
			if title == "" {
				title = page.Path
			}
			fmt.Fprintf(&builder, "- [%s](%s)\n", title, page.Path)
			index.Links = append(index.Links, PageLink{
				TargetPath: page.Path,
				LinkType:   LinkReferences,
			})
		}
	}
	index.Content = strings.TrimRight(builder.String(), "\n")
	index.ContentHash = hashContent(index.Content)
	return index
}

// buildLogPage renders the build events as an append-only timeline.
//
// The prefix format is stable on purpose so the log stays greppable with plain
// unix tools, which is how an operator reads it when the API is not at hand.
func buildLogPage(events []BuildEvent) WikiPage {
	var builder strings.Builder
	builder.WriteString("# Build log\n")
	for _, event := range events {
		fmt.Fprintf(&builder, "\n## [%s] %s", event.OccurredAt.UTC().Format("2006-01-02T15:04:05Z"), event.EventType)
		if event.PagePath != "" {
			fmt.Fprintf(&builder, " | %s", event.PagePath)
		}
		builder.WriteString("\n")
		if event.Detail != "" {
			fmt.Fprintf(&builder, "%s\n", event.Detail)
		}
	}
	page := WikiPage{
		Path:    "wiki/log.md",
		Kind:    PageKindLog,
		Title:   "Build log",
		Content: strings.TrimRight(builder.String(), "\n"),
	}
	page.ContentHash = hashContent(page.Content)
	return page
}

func hashContent(content string) string {
	sum := sha256.Sum256([]byte(content))
	return hex.EncodeToString(sum[:])
}

// compilePerDocumentChars bounds how much of each source document reaches the
// prompt. A fixed per-document budget rather than a shared global one, so a
// single long file cannot crowd every other document out of the view.
func (s *Service) compilePerDocumentChars() int {
	return 12000
}
